### PR TITLE
Text tracks and media status event handling

### PR DESCRIPTION
**Pull request by jcarolus**
- typing for MediaInfo
- added textTracks to handle subtitles
- removed get media info button because it's now updated via event
- added test change track button (this will become obsolete once the extended MediaController can open the track selector).
- added .editorconfig to match the current code style.

@lochstar it should be ready to merge.

### CODE REVIEW

**Comment by jcarolus** [comment]
@lochstar I would like to do some refactoring;
- move listener implementations to seperate files
- introduce cast.types.ts file for types
- move convertors (e.g. streamTypeStringToNumber) to convertors.[ios|android].ts

Is it ok if I make that part of this PR - or perhaps you have work in progress that best fits the current structure?

**Comment by lochstar** [comment]
That all sounds great. Feel free to make it part of this PR if that simplies things for you.

**Comment by jcarolus** [comment]
@lochstar do you have time to look into this merge? I would like to pick up some mini/expanded MediaController if needed.

**Comment by lochstar** [comment]
I'm back in the office tomorrow, so I should be able to take a look this week.

**Comment by jcarolus** [comment]
Awesome - mine is 5 yrs old now, welcome to the ride :)

If you can push your work in progress for the controllers, I can check it out and hopefully get something working for Android.

**Comment by lochstar** [comment]
I've just pasted the WIP iOS code in to a new issue: #8 

Good luck!

**Pull request merged**
